### ISSUE TITLE
Error creating synthetic bean: java.lang.ClassCastException

### ISSUE THREAD

**Issue by joe-specimen** [quarkiverse/quarkus-pooled-jms#325]
Hello @zhfeng

I am trying to integrate your pooling library inside my simple project. When I run the application everything works fine, but when I try to integrate your library for pooling inside the project I get the following exception:
```
2024-12-05 18:48:38,869 ERROR [org.acm.inf.ada.mes.MessageConsumerWorker] (pool-8-thread-1) Error creating synthetic bean [BDzP8T32aTgFW-MtQavWwwvvDK0]: java.lang.ClassCastException: class org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory cannot be cast to class org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory (org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory and org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @48f278eb): jakarta.enterprise.inject.CreationException: Error creating synthetic bean [BDzP8T32aTgFW-MtQavWwwvvDK0]: java.lang.ClassCastException: class org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory cannot be cast to class org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory (org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory and org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @48f278eb)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_Bean.doCreate(Unknown Source)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_Bean.create(Unknown Source)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c27(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_ClientProxy.createXAContext(Unknown Source)
	at org.acme.infrastructure.adapters.messaging.common.ArtemisJmsConsumer.receiveXA(ArtemisJmsConsumer.java:39)
	at org.acme.infrastructure.adapters.messaging.common.ArtemisJmsConsumer.receiveXA(ArtemisJmsConsumer.java:35)
	at org.acme.infrastructure.adapters.messaging.common.ArtemisJmsFactory_ProducerMethod_artemisJmsConsumerManager_48OMCSvMaqIjQC_IGzEfjMIJkSw_ClientProxy.receiveXA(Unknown Source)
	at org.acme.infrastructure.adapters.messaging.MessageConsumer.consume(MessageConsumer.java:21)
	at org.acme.infrastructure.adapters.messaging.MessageConsumer_Subclass.consume$$superforward(Unknown Source)
	at org.acme.infrastructure.adapters.messaging.MessageConsumer_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.infrastructure.adapters.messaging.MessageConsumer_Subclass.consume(Unknown Source)
	at org.acme.infrastructure.adapters.messaging.MessageConsumer_ClientProxy.consume(Unknown Source)
	at org.acme.infrastructure.adapters.messaging.MessageConsumerWorker.run(MessageConsumerWorker.java:38)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassCastException: class org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory cannot be cast to class org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory (org.messaginghub.pooled.jms.JmsPoolXAConnectionFactory and org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @48f278eb)
	at org.apache.activemq.artemis.jms.client.ActiveMQXAConnectionFactory_BDzP8T32aTgFW-MtQavWwwvvDK0_Synthetic_Bean.createSynthetic(Unknown Source)
```
Now I create my factory class looks folowing for consumer and producer objects:

```
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import jakarta.jms.ConnectionFactory;
import jakarta.jms.XAConnectionFactory;
import jakarta.transaction.TransactionManager;
import org.acme.infrastructure.adapters.messaging.common.ArtemisJmsConsumer;
import org.acme.infrastructure.adapters.messaging.common.ArtemisJmsProducer;

@ApplicationScoped
public class ArtemisJmsFactory {

   @Produces
   @ApplicationScoped
   ArtemisJmsConsumer artemisJmsConsumerManager(
       @SuppressWarnings("CdiInjectionPointsInspection") ConnectionFactory connectionFactory,
       @SuppressWarnings("CdiInjectionPointsInspection") XAConnectionFactory xaConnectionFactory,
       @SuppressWarnings("CdiInjectionPointsInspection") TransactionManager tm
   ) {
      return new ArtemisJmsConsumer(connectionFactory, xaConnectionFactory, tm);
   }

   @Produces
   @ApplicationScoped
   ArtemisJmsProducer artemisJmsProducerManager(
       @SuppressWarnings("CdiInjectionPointsInspection") ConnectionFactory connectionFactory,
       @SuppressWarnings("CdiInjectionPointsInspection") XAConnectionFactory xaConnectionFactory,
       @SuppressWarnings("CdiInjectionPointsInspection") TransactionManager tm
   ) {
      return new ArtemisJmsProducer(connectionFactory, xaConnectionFactory, tm);
   }

}

```
my application.properties look like following (exerpt):

```
## Jms
quarkus.artemis.devservices.enabled=false
quarkus.artemis.enabled=true
quarkus.artemis.url=tcp://localhost:61616
quarkus.artemis.username=admin
quarkus.artemis.password=admin
quarkus.artemis.health-exclude=true
quarkus.artemis.xa-enabled=true
### Quarkus Messaginghub Pooled JMS
quarkus.pooled-jms.transaction=xa
```
I really do not know where I am missing something.

**Comment by zhfeng** [comment]
Can you share `ArtemisJmsConsumer` and `ArtemisJmsProducer`? As far as I know, `quarkus-pooled-jms` can work with `quarkus-artemis-jms`, so there is no need to have any other code and just use `ConnectionFactory`
```java
   @Produces
   @ApplicationScoped
   ArtemisJmsConsumer artemisJmsConsumerManager(
       @SuppressWarnings("CdiInjectionPointsInspection") ConnectionFactory connectionFactory)
   ) {
      return new ArtemisJmsConsumer(connectionFactory);
   }
```

**Comment by joe-specimen** [comment]
@zhfeng 
Here you can take a look at the project where consumer and producer are located (it is really short one):
https://github.com/joe-specimen/acme-xa-messaging-consumer/tree/main/src/main/java/org/acme/infrastructure/adapters/messaging

**Comment by zhfeng** [comment]
OK, so in `receiveXA` there is no need to invoke `enlist`. And it should be enlisted automatically if you add `quarkus-pooled-jms` and config it with `quarkus.pooled-jms.transaction=xa`.

And as I said above, don't need to use `XAConnectionFatory`. You could only use `ConnectionFactory` and it can work both in XA or non-XA transaction.

**Comment by joe-specimen** [comment]
Hi @zhfeng, 
I have updated the code how according  to your instructions, but I still get the same error described above. I have checked in my changes into the repo I gave you link: If you wish you can try it out.

**Comment by zhfeng** [comment]
@joe-specimen 

Please try to comment `quarkus.artemis.xa-enabled=true`, this is not needed anymore.

**Comment by zhfeng** [comment]
See my changes https://github.com/joe-specimen/acme-xa-messaging-consumer/pull/1

**Comment by joe-specimen** [comment]
Hi @zhfeng . Thank you very much for the corrections 👍. Now it works. What I wanted to ask you is why was the reason that you put the `TransactionManager`  inside of the producer method signature? Is there any special reason. Can this pooling functionality be also integrated with smallrye reactive messaging (amqp connector)?

**Comment by zhfeng** [comment]
> What was the reason that you put the TransactionManager inside of the producer method?

Well, it is because the producer method bean is not controlled by Quarkus Arc container, the @Inject does not work in `ArtemisJmsConsumer`

> Can this pooling functionality be also integrated with smallrye reactive messaging (amqp connector)?

No, it does not. But it supports to be integrated with [quarkus-qpid-jms ](https://github.com/amqphub/quarkus-qpid-jms)

**Comment by joe-specimen** [comment]
Thank you very, very much for your help 🫡.  You really helped me a lot.
I have one last question. 
Is there a way to know how many of the pooled connections/sessions are in use or not in use?

**Comment by zhfeng** [comment]
I think we can leverage [quarkus-micrometer](https://quarkus.io/guides/telemetry-micrometer) for collecting metrics. So feel free to create an issue and welcom contributions!
